WebApplication1/WebApplication1/Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections;
using System.Web.Mvc;
using WebApplication1.App_Class;
using System.Data.Entity;
using System.Threading;
using System.Web.Security;
using System.Globalization;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class adminController : Controller
    {

        erp_KaderGUREntities db = Context.Baglanti;

        [HttpPost]
        [Authorize(Roles = "IT,F,SP")]
        public ActionResult isortagiFatura(int IsOrtaklariId)
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            return View(Context.Baglanti.Faturalar.SqlQuery("select * from Faturalar where IsOrtaklariID=" + IsOrtaklariId).ToList());
            //return View(Context.Baglanti.spFaturaGetirIsOrtagiId(IsOrtaklariId).ToList());
        }
        public ActionResult faturalar()
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            return View(Context.Baglanti.Faturalar.ToList());
        }

        [Authorize(Roles = "IT")]
        public ActionResult kullanicilarIT()
        {
            //return View(Context.Baglanti.spKullaniciItGetir());
            return View(Context.Baglanti.Kullanici.SqlQuery("select * from Kullanici where DepartmanID=1"));
        }
        public ActionResult kullanicilarIK()
        {
            return View(Context.Baglanti.Kullanici.SqlQuery("select * from Kullanici where DepartmanID=3"));
        }
        public ActionResult kullanicilarSP()
        {
            return View(Context.Baglanti.Kullanici.SqlQuery("select * from Kullanici where DepartmanID=4"));
        }
        public ActionResult kullanicilarF()
        {
            return View(Context.Baglanti.Kullanici.SqlQuery("select * from Kullanici where DepartmanID=2"));
        }
        public ActionResult RolOnayla()
        {
            return View(Context.Baglanti.Kullanici.Where(x => x.Role == "U"));
        }
        [HttpPost]
        public ActionResult RolOnayla(int RolOnayla)
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            Kullanici onayliKullanici = Context.Baglanti.Kullanici.Find(RolOnayla);
            if (onayliKullanici.DepartmanID == 1)
            {
                onayliKullanici.Role = "IT";
            }
            else if (onayliKullanici.DepartmanID == 2)
            {
                onayliKullanici.Role = "F";
            }
            else if (onayliKullanici.DepartmanID == 3)
            {
                onayliKullanici.Role = "IK";
            }
            else if (onayliKullanici.DepartmanID == 4)
            {
                onayliKullanici.Role = "SP";
            }
            db.Entry(onayliKullanici).State = EntityState.Modified;
            Context.Baglanti.SaveChanges();
            return View(Context.Baglanti.Kullanici.Where(x => x.Role == "U"));
        }

        [Authorize(Roles = "IT,IK")]
        public ActionResult personeller()
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            db = new erp_KaderGUREntities();
            return View(Context.Baglanti.Personel.ToList());
        }
        public ActionResult personelEkle()
        {
            //ViewBag.Departman = Context.Baglanti.Departman.SqlQuery("select * from Departman where KullaniciDepartmani=0");
            ViewBag.Departman = Context.Baglanti.Departman.Where(x => x.KullaniciDepartmani == false);
            return View();
        }
        [HttpPost]
        public ActionResult personelEkle(Personel prsnl)
        {
            Context.Baglanti.Personel.Add(prsnl);
            Context.Baglanti.SaveChanges();
            return RedirectToAction("personeller");
        }
        [HttpPost]
        public ActionResult personelSil(int personelSil)
        {
            Context.Baglanti.spPersonelSil(personelSil);
            Context.Baglanti.SaveChanges();
            return RedirectToAction("personeller");
        }
        [HttpPost]
        public ActionResult personelGuncelle(int personelSil)
        {
            ViewBag.Departman = Context.Baglanti.Departman.SqlQuery("select * from Departman where KullaniciDepartmani=0");
            //return View(Context.Baglanti.Personel.SqlQuery("select * from Personel where PersonelId=" + personelSil));
            return View(Context.Baglanti.Personel.Find(personelSil));
        }
        [HttpPost]
        public ActionResult personelGuncelleOnay(Personel prsnl)
        {
            Personel prsnlNew = Context.Baglanti.Personel.Find(prsnl.PersonelId);
            prsnlNew.AdSoyad = prsnl.AdSoyad;
            prsnlNew.DepartmanID = prsnl.DepartmanID;
            prsnlNew.Email = prsnl.Email;
            prsnlNew.Gsm = prsnl.Gsm;
            prsnlNew.iseGirisTarihi = prsnl.iseGirisTarihi;
            prsnlNew.Maas = prsnl.Maas;
            prsnlNew.TC = prsnl.TC;

            //Context.Baglanti.spPersonelGuncelle(prsnl.PersonelId, prsnl.AdSoyad, prsnl.TC, prsnl.Email, prsnl.Gsm, prsnl.iseGirisTarihi, prsnl.DepartmanID, prsnl.Maas);
            //Context.Baglanti.Personel.SqlQuery("update Personel set AdSoyad={0},TC={1},Email={2},Gsm={3},iseGirisTarihi={4},DepartmanID={5},Maas={6} where PersonelId={7}", prsnl.AdSoyad, prsnl.TC, prsnl.Email, prsnl.Gsm, prsnl.iseGirisTarihi, prsnl.DepartmanID, prsnl.Maas, prsnl.PersonelId);
            //Personel guncellenecekpersonel = Context.Baglanti.Personel.Where(w => w.PersonelId == prsnl.PersonelId).FirstOrDefault();

            db.Entry(prsnlNew).State = EntityState.Modified;
            Context.Baglanti.SaveChanges();
            return RedirectToAction("personeller");
        }

        [Authorize(Roles = "IT,F")]
        public ActionResult isOrtaklariEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult isOrtaklariEkle(IsOrtaklari isOrtaklari)
        {
            Context.Baglanti.IsOrtaklari.Add(isOrtaklari);
            Context.Baglanti.SaveChanges();
            return RedirectToAction("isortaklari");
        }

        [Authorize(Roles = "IT,F,SP")]
        public ActionResult isortaklari()
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            return View(Context.Baglanti.IsOrtaklari.ToList());
        }
        [HttpPost]
        public ActionResult IsOrtaklariSil(int IsOrtaklariSil)
        {
            Context.Baglanti.spIsOrtaklariSil(IsOrtaklariSil);
            Context.Baglanti.SaveChanges();
            return RedirectToAction("isortaklari");
        }
        [HttpPost]
        public ActionResult IsOrtaklariGuncelle(int IsOrtaklariGuncelle)
        {
            return View(Context.Baglanti.IsOrtaklari.Find(IsOrtaklariGuncelle));
            //return View(Context.Baglanti.IsOrtaklari.SqlQuery("select * from IsOrtaklari where IsOrtaklariId=" + IsOrtaklariGuncelle));
        }
        [HttpPost]
        public ActionResult IsOrtaklariGuncelleOnay(IsOrtaklari isOrtaklari)
        {
            IsOrtaklari ısOrtagiYeni = Context.Baglanti.IsOrtaklari.Find(isOrtaklari.IsOrtaklariId);
            ısOrtagiYeni.FirmaAd = isOrtaklari.FirmaAd;
            ısOrtagiYeni.Adres = isOrtaklari.Adres;
            ısOrtagiYeni.Email = isOrtaklari.Email;
            ısOrtagiYeni.Gsm = isOrtaklari.Gsm;

            db.Entry(ısOrtagiYeni).State = EntityState.Modified;
            Context.Baglanti.SaveChanges();
            return RedirectToAction("isortaklari");
        }

        public ActionResult profil()
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            return View(Context.Baglanti.Kullanici.Where(x => x.Email == (HttpContext.User.Identity.Name)));
            //return View(Context.Baglanti.Kullanici.Find(HttpContext.User.Identity.Name));
        }

        [HttpPost]
        public ActionResult profilDuzenle(int kullaniciId)
        {
            ViewBag.OnayBekleyenAdet = Context.Baglanti.Kullanici.Count(x => x.Role == "U");
            ViewBag.OkunmamisDilekceSayisi = Context.Baglanti.Dilekce.Count(x => x.Okundu == false);
            ViewBag.Departman = Context.Baglanti.Departman.SqlQuery("select * from Departman where KullaniciDepartmani=1");
            return View(Context.Baglanti.Kullanici.Find(kullaniciId));
            //return View(Context.Baglanti.Kullanici.SqlQuery("select * from Kullanici where KullaniciId=" + kullaniciId));
        }

        [HttpPost]
        public ActionResult profilDuzenleOnay(Kullanici kullanici)
        {
            Kullanici kullaniciYeni = Context.Baglanti.Kullanici.Find(kullanici.KullaniciId);
            kullaniciYeni.AdSoyad = kullanici.AdSoyad;
            kullaniciYeni.DogumTarihi = kullanici.DogumTarihi;
            kullaniciYeni.Email = kullanici.Email;
            kullaniciYeni.Gsm = kullanici.Gsm;
            kullaniciYeni.DepartmanID = kullanici.DepartmanID;
            kullaniciYeni.Sifre = kullanici.Sifre;
            db.Entry(kullaniciYeni).State = EntityState.Modified;
            Context.Baglanti.SaveChanges();
            return RedirectToAction("profil");
        }

        public ActionResult admin()
        {

WebApplication1/WebApplication1/Views/admin/RolOnayla.cshtml
@{
    ViewBag.Title = "RolOnayla";
    Layout = "~/Views/admin/layout.cshtml";
}

@model IEnumerable<WebApplication1.Kullanici>

<section class="panel">
    <div class="panel-body">
        <div class="adv-table editable-table ">
            <header class="panel-heading">
                <h4>@WebApplication1.Language.Localization.OnayBekleyen</h4>
            </header>
            <br />
            <div class="space15"></div>
            <table class="table table-striped table-hover table-bordered" id="editable-sample">
                <thead>
                    <tr>
                        <th>TC</th>
                        <th>@WebApplication1.Language.Localization.AdSoyad</th>
                        <th>@WebApplication1.Language.Localization.DogumTarihi</th>
                        <th>@WebApplication1.Language.Localization.Email</th>
                        <th>@WebApplication1.Language.Localization.Telefon</th>
                        <th>@WebApplication1.Language.Localization.Departman</th>
                        <th>@WebApplication1.Language.Localization.Onayla</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="">
                            <td>@item.TC</td>
                            <td>@item.AdSoyad</td>
                            <td>@item.DogumTarihi</td>
                            <td>@item.Email</td>
                            <td>@item.Gsm</td>
                            <td>@item.Departman.DepartmanAd</td>
                            <td>
                                <form name="RolOnayla" action="/admin/RolOnayla" role="form" method="post">
                                    <button name="RolOnayla" value="@item.KullaniciId" type="submit" class="btn btn-success btn-xs"> <i class="icon-ok"></i></button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

WebApplication1/WebApplication1/Views/admin/cvler.cshtml
@{
    ViewBag.Title = "cvler";
    Layout = "~/Views/admin/layout.cshtml";
}

<h2>cvler</h2>

WebApplication1/WebApplication1/Views/admin/dilekceler.cshtml
@{
    ViewBag.Title = "dilekceler";
    Layout = "~/Views/admin/layout.cshtml";
}
@model IEnumerable<WebApplication1.Dilekce>

<div class="row">
    <div class="col-md-12">
        <section class="panel tasks-widget">
            <header class="panel-heading">
                @*@WebApplication1.Language.Localization.Dilekceler*@
            </header>
            <div class="panel-body">
                <div class="task-content">
                    <ul class="task-list">
                        <table class="table table-striped table-hover table-bordered" id="editable-sample">
                            <thead>
                                <tr>
                                    <th>@WebApplication1.Language.Localization.Dilekceler</th>
                                    <th>@WebApplication1.Language.Localization.Islemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.Baslik
                                            @{
                                                TimeSpan ts = DateTime.Now - Convert.ToDateTime(item.Tarih);
                                                <span class="badge badge-sm label-success"> @ts.Days @WebApplication1.Language.Localization.GunOnce</span>
                                            }
                                        </td>
                                        <td><button class="btn btn-danger btn-xs"><i class="icon-ok"></i></button></td>
                                    </tr>
                                }
                            </tbody>

                            @*<div class="task-title">
                                    <a href="" class="task-title-sp">@item.Baslik </a>
                                    @{
                                        TimeSpan ts = DateTime.Now - Convert.ToDateTime(item.Tarih);
                                        <span class="badge badge-sm label-success"> @ts.Days @WebApplication1.Language.Localization.GunOnce</span>
                                    }
                                    <div class="pull-right hidden-phone">
                                        <form class="horizontal-menu">
                                            <button class="btn btn-danger btn-xs"><i class="icon-ok"></i></button>
                                        </form>
                                        <button class="btn btn-primary btn-xs"><i class="icon-pencil"></i></button>
                                        <button class="btn btn-danger btn-xs"><i class="icon-trash "></i></button>
                                    </div>
                                </div>*@
                        </table>
                    </ul>
                </div>
            </div>
        </section>
    </div>
</div>

WebApplication1/WebApplication1/Views/admin/layout.cshtml
@{
    Layout = null;
}
@using WebApplication1.App_Class;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="~/img/favicon.png">

    <title>Admin Paneli</title>

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />

    <!--DateTimePicker-->
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-fileupload/bootstrap-fileupload.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-datepicker/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-timepicker/compiled/timepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-colorpicker/css/colorpicker.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-daterangepicker/daterangepicker-bs3.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-datetimepicker/css/datetimepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/jquery-multi-select/css/multi-select.css" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="~/js/html5shiv.js"></script>
      <script src="~/js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a href="/admin/admin" class="logo">GUR<span>Mensucat</span></a>
            <!--logo end-->
            
            <div class="top-nav ">
                <!--search & user info start-->
                <ul class="nav pull-right top-menu">
                    <!-- user login dropdown start-->
                    <li class="dropdown language">
                        <form name="DilSec" method="post" action="/admin/DilSec" role="form">
                            <button name="secilenDil" type="submit" value="tr" class="btn btn-shadow btn-default btn-sm">
                                <img src="~/img/flags/tr.png">
                                <span>Türkçe</span>
                            </button>
                            <button name="secilenDil" type="submit" value="en" class="btn btn-shadow btn-default btn-sm">
                                <img src="~/img/flags/us.png">
                                <span>English</span>
                            </button>
                        </form>
                        @*@Html.ActionLink("Türkçe", "DilSec", "admin", new { secilenDil = "tr" }, new { @class = "btn btn-default" })
                            @Html.ActionLink("English", "DilSec", "admin", new { secilenDil = "en" }, new { @class = "btn btn-default" })*@
                    </li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="~/#">
                            <span class="username">@HttpContext.Current.User.Identity.Name</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            <li><a href="/admin/profil"><i class=" icon-suitcase"></i>Profil</a></li>
                            <li><a href="/admin/cikis"><i class="icon-key"></i>@WebApplication1.Language.Localization.Cikis</a></li>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!--search & user info end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a class="@Html.ActivePage("admin","admin")" href="/admin/admin">
                            <i class="icon-th"></i>
                            @*<span name="Anasayfa">Anasayfa</span>*@
                            <span>@WebApplication1.Language.Localization.Anasayfa</span>
                        </a>
                    </li>
                    @if (User.IsInRole("IT"))
                    {
                        <li class="sub-menu">
                            <a href="javascript:;">
                                <i class="icon-sitemap"></i>
                                @*<span name="Kullanicilar">Kullanıcılar</span>*@
                                <span>@WebApplication1.Language.Localization.Kullanicilar</span>
                            </a>
                            <ul class="sub">
                                <li><a class="@Html.ActivePage("admin","kullanicilarIT")" href="/admin/kullanicilarIT">@WebApplication1.Language.Localization.KullanicilarIT</a> </li>
                                <li><a class="@Html.ActivePage("admin","kullanicilarIK")" href="/admin/kullanicilarIK">@WebApplication1.Language.Localization.KullanicilarIK</a> </li>
                                <li><a class="@Html.ActivePage("admin","kullanicilarSP")" href="/admin/kullanicilarSP">@WebApplication1.Language.Localization.KullanicilarSP</a> </li>
                                <li><a class="@Html.ActivePage("admin","kullanicilarF")" href="/admin/kullanicilarF">@WebApplication1.Language.Localization.KullanicilarF</a> </li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("IT") || User.IsInRole("IK"))
                    {
                        <li>
                            <a class="@Html.ActivePage("admin","personeller")" href="/admin/personeller">
                                <i class="icon-group"></i>
                                <span>@WebApplication1.Language.Localization.Personeller</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("IT") || User.IsInRole("F") || User.IsInRole("SP"))
                    {
                        <li>
                            <a class="@Html.ActivePage("admin","faturalar")" href="/admin/faturalar">
                                <i class="icon-archive"></i>
                                <span>@WebApplication1.Language.Localization.Faturalar</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("IK") || User.IsInRole("IT"))
                    {
                        <li>
                            <a class="@Html.ActivePage("admin","dilekceler")" href="/admin/dilekceler">
                                <i class="icon-comments-alt"></i>
                                <span>@WebApplication1.Language.Localization.Dilekceler</span>
                                <span class="label label-danger pull-right mail-info">@ViewBag.OkunmamisDilekceSayisi</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("IT") || User.IsInRole("F") || User.IsInRole("SP"))
                    {
                        <li>
                            <a class="@Html.ActivePage("admin","isortaklari")" href="/admin/isortaklari">
                                <i class="icon-suitcase"></i>
                                <span>@WebApplication1.Language.Localization.IsOrtaklari</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("IT"))
                    {
                        <li>
                            <a class="@Html.ActivePage("admin","RolOnayla")" href="/admin/RolOnayla">
                                <i class="icon-ok-sign"></i>
                                <span>@WebApplication1.Language.Localization.OnayBekleyen</span>
                                    <span class="label label-danger pull-right mail-info">@ViewBag.OnayBekleyenAdet</span>
                            </a>
                        </li>
                    }
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                @WebApplication1.Language.Localization.Footer
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery-1.8.3.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/js/owl.carousel.js"></script>
    <script src="~/js/jquery.customSelect.min.js"></script>
    <script src="~/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="~/js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="~/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="~/js/sparkline-chart.js"></script>
    <script src="~/js/easy-pie-chart.js"></script>
    <script src="~/js/count.js"></script>

    <!--DateTimePicker-->
    <script type="text/javascript" src="~/assets/fuelux/js/spinner.min.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-fileupload/bootstrap-fileupload.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-daterangepicker/moment.min.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
    <script type="text/javascript" src="~/assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
    <script type="text/javascript" src="~/assets/jquery-multi-select/js/jquery.multi-select.js"></script>
    <script type="text/javascript" src="~/assets/jquery-multi-select/js/jquery.quicksearch.js"></script>
    <!--this page  script only-->
    <script src="~/js/advanced-form-components.js"></script>


    <script>

        //owl carousel

        $(document).ready(function () {
            $("#owl-demo").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true,
                autoPlay: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

    </script>

</body>
</html>

WebApplication1/WebApplication1/Views/admin/personelEkleBasarili.cshtml
@{
    ViewBag.Title = "personelEkleBasarılı";
    Layout = "~/Views/admin/layout.cshtml";
}

<h2>Başarılı</h2>